version: "2"
services:
  green:
    image: "node:8-alpine"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - NPM_CONFIG_PREFIX=/home/node/.npm-global
    volumes:
      - ./:/home/node/app
    ports:
      - ${PORT}:${PORT}
    command: "npm start"